import {chromium} from 'playwright';
import AxeBuilder from '@axe-core/playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {materials,journeys} from '../src/data.js';
const browser=await chromium.launch({headless:true,...(process.env.BROWSER_CHANNEL?{channel:process.env.BROWSER_CHANNEL}:{})});
const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const base=process.env.TEST_URL||'http://127.0.0.1:4173/';
const results=[];await fs.mkdir('docs/screenshots',{recursive:true});
async function go(route){await page.goto(base+'#/'+route);await page.locator('h1').waitFor();assert.ok(!await page.getByText('A thread we couldn’t follow.',{exact:true}).count(),'Unexpected route failure: '+route);}
try{
 await go('atlas/wool');assert.equal(await page.locator('.fiber-option').count(),30);await page.getByRole('button',{name:'Zoom in',exact:true}).click();await page.getByRole('button',{name:'Reset globe'}).click();await page.getByRole('button',{name:'Map',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Map',exact:true}).getAttribute('aria-pressed'),'true');await page.getByRole('button',{name:'Globe',exact:true}).click();await page.getByRole('button',{name:'Dubbo Grower',exact:false}).click();assert.ok(await page.locator('.node-detail').count());await page.getByRole('button',{name:'Close place detail'}).click();await page.getByRole('button',{name:'Reset globe'}).click();await page.screenshot({path:'docs/screenshots/atlas-desktop.png',fullPage:true});results.push('Atlas: globe/map, zoom/reset and node details');
 await go('materials');await page.getByLabel('Search material library').fill('pashmina');assert.equal(await page.locator('.material-card').count(),1);assert.ok(await page.getByRole('heading',{name:'Cashmere',exact:true}).count());await page.getByRole('button',{name:'Reset',exact:true}).click();await page.locator('#library-family').selectOption('Plant');await page.locator('#library-sort').selectOption('az');assert.ok(await page.locator('.material-card').count()>1);await page.getByRole('button',{name:'Save Abacá',exact:true}).click();await go('saved');assert.ok(await page.getByRole('heading',{name:'Abacá',exact:true}).count());await page.reload();assert.ok(await page.getByRole('heading',{name:'Abacá',exact:true}).count());results.push('Library: search aliases, filter, sort, save and reload persistence');
 await go('compare');await page.locator('#compare-0').selectOption('cashmere');await page.waitForURL(/cashmere/);assert.ok(await page.locator('table').getByText('Cashmere',{exact:true}).count());results.push('Comparison selects update URL and content');
 await go('science');await page.getByRole('button',{name:'2/2 twill',exact:true}).click();assert.equal(await page.getByRole('button',{name:'2/2 twill',exact:true}).getAttribute('aria-pressed'),'true');await page.locator('#denier').fill('0');assert.match(await page.locator('#diameter').textContent(),/valid/);await page.locator('#denier').fill('5');assert.match(await page.locator('#diameter').textContent(),/22.64/);await page.screenshot({path:'docs/screenshots/science-desktop.png',fullPage:true});results.push('Science: weave switching, invalid values and numeric output');
 await page.getByRole('button',{name:'Search the atlas'}).click();await page.getByRole('searchbox',{name:'Search all materials, journeys and field notes'}).fill('ECONYL');await page.locator('.search-result').first().click();await page.waitForURL(/fiber\/econyl/);assert.equal(await page.locator('dialog[open]').count(),0);results.push('Global search routes and closes its dialog');
 for(const m of (process.env.QUICK_TEST?[]:materials)){await go('fiber/'+m.id);assert.ok(await page.getByRole('heading',{name:m.name,exact:true}).count());}for(const j of (process.env.QUICK_TEST?[]:journeys)){await go('journey/'+j.id);}if(!process.env.QUICK_TEST)results.push('All 100 material profiles and 115 journey detail routes render');
 for(const t of ['overview','history','science','journeys','care'])await go('fiber/wool/'+t);
 for(const path of ['atlas/wool','materials','brands','compare','journeys','regions','learn','science','history','glossary','sources','about','privacy']){
  await go(path);const a=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();const violations=a.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)}));if(violations.length)results.push({accessibility:path,violations});
  for(const width of [1440,768,390]){await page.setViewportSize({width,height:900});const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);if(overflow)console.log('OVERFLOW',path,width,await page.evaluate(()=>[...document.querySelectorAll('body *')].filter(x=>x.getBoundingClientRect().right>innerWidth+1).map(x=>({tag:x.tagName,class:x.className,right:x.getBoundingClientRect().right})).slice(0,15)));assert.equal(overflow,false,'Horizontal overflow: '+path+' @ '+width);}
 }
 results.push('All main sections checked at 1440, 768 and 390 pixels');
 await page.setViewportSize({width:390,height:844});await go('atlas/wool');await page.screenshot({path:'docs/screenshots/atlas-mobile.png',fullPage:true});await go('materials');await page.screenshot({path:'docs/screenshots/library-mobile.png',fullPage:true});
 await page.setViewportSize({width:1440,height:1000});await go('materials');await page.screenshot({path:'docs/screenshots/library-desktop.png',fullPage:true});
 await page.goto(base+'#/fiber/%3Cscript%3E');assert.ok(await page.getByRole('heading',{name:'A thread we couldn’t follow.'}).count());await page.goto(base+'#/materials?q=%3Cimg%20src=x%20onerror=alert(1)%3E');assert.equal(await page.locator('#main img').count(),0);results.push('Unknown routes and escaped search input handled');
 await context.setOffline(true);await page.goto(new URL('../index.html',import.meta.url).href+'#/materials');await page.locator('h1').waitFor();assert.ok(await page.locator('.material-card').count()>0);results.push('Standalone HTML opens offline with populated library');
 assert.deepEqual(errors,[]);results.push('No browser JavaScript errors');
 await fs.writeFile('docs/browser-results.json',JSON.stringify({date:'2026-09-22',browser:'Chromium',results},null,2));console.log(JSON.stringify(results,null,2));assert.equal(results.filter(x=>x.violations?.length).length,0,'Accessibility violations');
}catch(e){await page.screenshot({path:'docs/screenshots/failure.png',fullPage:true});console.error(e);console.log(JSON.stringify(results,null,2));process.exitCode=1;}finally{await browser.close();}
