import fs from 'node:fs/promises';
import {glossaryEntries,findTerms,reviewed} from '../src/glossary.js';
import {termBody,escapeHTML as e} from '../src/glossary-render.js';
export async function buildGlossary(css){
 const base=new URL(process.env.SITE_URL||'https://sharpmeow.github.io/FibersOfEarth/');
 if(!['http:','https:'].includes(base.protocol)||base.search||base.hash)throw Error('SITE_URL must be an HTTP(S) site URL without a query or fragment');
 if(!base.pathname.endsWith('/'))base.pathname+='/';
 const url=p=>new URL(p,base).href;
 const json=x=>JSON.stringify(x).replaceAll('<','\\u003c');
 const terms=findTerms();
 function page({name,description,path,body,schema,depth}){const home=depth?'../../':'../',index=depth?'../index.html':'index.html';return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(name)} | Fibers of Earth</title><meta name="description" content="${e(description)}"><link rel="canonical" href="${e(url(path))}"><meta property="og:type" content="website"><meta property="og:title" content="${e(name)}"><meta property="og:description" content="${e(description)}"><meta property="og:url" content="${e(url(path))}"><meta name="twitter:card" content="summary"><style>${css}</style><script type="application/ld+json">${json(schema)}</script></head><body><a class="skip" href="#main">Skip to content</a><header><nav class="glossary-static-nav" aria-label="Main navigation"><a href="${home}index.html">Fibers of Earth</a><a href="${index}">Textile glossary</a><a href="${home}index.html#/materials">Materials</a><a href="${home}index.html#/science">Science lab</a></nav></header><main id="main" class="page ${depth?'glossary-article':''}">${body}</main><footer class="site-footer"><p>Fibers of Earth · An independent field guide by Chaos.</p><a href="${home}index.html#/sources">Sources & method</a></footer></body></html>`;}
 const files=new Map();
 const indexPath='glossary/index.html';
 files.set(indexPath,page({name:'Textile glossary: fiber, fabric & processing definitions',description:`Explore ${terms.length} textile definitions with the science behind each term, practical examples, origins, related terms and sources, from bast fiber and denier to weaving and worsted.`,path:'glossary/',depth:0,schema:{'@context':'https://schema.org','@type':'DefinedTermSet',name:'Fibers of Earth textile glossary',url:url('glossary/'),hasDefinedTerm:terms.map(t=>({'@type':'DefinedTerm',name:t.term,url:url('glossary/'+t.id+'/'),description:t.definition}))},body:`<div class="page-intro"><div class="eyebrow">THE LANGUAGE OF TEXTILES</div><h1>Textile glossary.</h1><p>Detailed definitions of fiber structure, fabric construction, measurements, processing and sourcing claims. Start with a short answer, then explore how the term is used and what it does not tell you.</p><p class="editorial-note">${terms.length} entries · Technical references reviewed ${reviewed} · Original explanations by Chaos.</p><a href="../index.html#/glossary">Search and filter in the interactive glossary ↗</a></div><nav class="family-chips" aria-label="Jump to letter">${[...new Set(terms.map(t=>t.term[0]))].map(l=>`<a class="chip" href="#letter-${l}">${l}</a>`).join('')}</nav><ul class="glossary-static-list">${terms.map((t,i)=>`<li${i===0||terms[i-1].term[0]!==t.term[0]?` id="letter-${t.term[0]}"`:''}><div class="eyebrow">${e(t.category)}</div><h2><a href="${t.id}/index.html">${e(t.term)}</a></h2><p>${e(t.definition)}</p></li>`).join('')}</ul>`}));
 for(const t of terms){const path='glossary/'+t.id+'/';files.set(path+'index.html',page({name:t.term+': definition, examples & textile uses',description:t.definition,path,depth:1,schema:{'@context':'https://schema.org','@graph':[{'@type':'DefinedTerm','@id':url(path)+'#term',name:t.term,alternateName:t.aliases,description:t.definition,url:url(path),inDefinedTermSet:url('glossary/')},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Textile glossary',item:url('glossary/')},{'@type':'ListItem',position:2,name:t.term,item:url(path)}]}]},body:`<nav class="breadcrumb" aria-label="Breadcrumb"><a href="../index.html">Textile glossary</a><span> / ${e(t.term)}</span></nav><div class="eyebrow">${e(t.category)}</div><h1>${e(t.term)}</h1><p class="muted">Also searched as: ${t.aliases.map(e).join(', ')}</p><div class="reading">${termBody(t,id=>'../'+id+'/index.html')}</div>`}));}
 for(const [path,html] of files){for(const root of ['dist','.']){await fs.mkdir(root+'/'+path.slice(0,path.lastIndexOf('/')),{recursive:true});await fs.writeFile(root+'/'+path,html);}}
 const sitemap=`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['glossary/',...terms.map(t=>'glossary/'+t.id+'/')].map(path=>`<url><loc>${e(url(path))}</loc><lastmod>${reviewed}</lastmod></url>`).join('')}</urlset>`;
 for(const root of ['dist','.'])await fs.writeFile(root+'/sitemap.xml',sitemap);
 console.log(`Built ${files.size} readable glossary pages and sitemap for ${base.href}`);
}
