// Brand descriptions are attributed to their publishers. No affiliation or performance endorsement.
const rows=[
 ['tencel','TENCEL™','Branded fiber family','lyocell','Lenzing’s brand includes lyocell and modal products. Read the generic composition to identify which fiber is present.','The brand’s history follows the commercial development and branding of regenerated cellulose. Its portfolio spans more than one generic fiber type.','https://www.lenzing.com/technology-production/technologies/'],
 ['ecovero','LENZING™ ECOVERO™','Branded viscose','viscose','A Lenzing viscose brand with producer-specific sourcing and process claims. Those claims should be checked for the particular product.','The brand developed around differentiated viscose sourcing and production. Its range later incorporated products using REFIBRA technology.','https://www.lenzing.com/products/brands/lenzingtm-ecoverotm/'],
 ['refibra','REFIBRA™','Feedstock technology','lyocell','Lenzing technology that incorporates recovered cellulose inputs into selected fiber products. The actual recycled share depends on the product.','REFIBRA has been associated with TENCEL lyocell and was extended to ECOVERO viscose. It identifies a technology rather than a separate generic fiber.','https://www.lenzing.com/newsroom/news-events/lenzing-expands-refibratm-technology-to-lenzingtm-ecoverotm-setting-new-responsible-viscose-standards-for-textile-circularity/'],
 ['econyl','ECONYL®','Regenerated nylon brand','recycled-nylon','Aquafil’s regenerated nylon brand. Identify the product, composition and documented waste inputs rather than assuming all feedstock is fishing nets.','The brand connects nylon recovery with new yarn and product applications. It is a branded route within polyamide recycling, not a new natural fiber.','https://econyl.aquafil.com/'],
 ['repreve','REPREVE®','Recycled-material platform','recycled-polyester','UNIFI’s brand spans recycled polyester, nylon and related products. Waste streams and product specifications vary within the platform.','REPREVE expanded from recycled-fiber branding into multiple feedstock and product lines. FiberPrint and U-TRUST are associated traceability tools.','https://repreve.com/'],
 ['seaqual','SEAQUAL® YARN','Recycled-yarn program','recycled-polyester','A yarn program associated with recovered marine plastic. Check the exact composition and marine-derived share of the specified yarn.','SEAQUAL connects collection and polymer processing with yarn partners. The program name does not describe the entire composition of every finished fabric.','https://www.seaqual.org/seaqual-yarn/'],
 ['spinnova','SPINNOVA®','Fiber technology','paper-yarn','A proprietary fiber-forming technology and ingredient brand using cellulose-rich inputs. It is distinct from ordinary viscose processing.','Spinnova’s development centers on turning a cellulose suspension into textile fiber. Commercial status and manufacturing capacity should be checked with the producer.','https://spinnova.com/fibre/'],
 ['infinna','Infinna™','Regenerated fiber brand','viscose','Infinited Fiber Company’s branded cellulose fiber made using its proprietary technology and textile-waste inputs.','Infinna developed as part of efforts to return cellulose-rich textile waste to fiber production. Pilot work, planned capacity and actual commercial supply are different milestones.','https://infinitedfiber.com/'],
 ['circulose','CIRCULOSE®','Recycled dissolving pulp','viscose','A recycled-cellulose pulp feedstock used by downstream fiber producers. It is not, by itself, the finished fiber name on a garment.','CIRCULOSE belongs to the development of textile-to-textile cellulose feedstocks. Its path continues through a separate fiber-making process before yarn and fabric.','https://circulose.com/'],
 ['naia','Naia™','Cellulose-acetate brand','acetate','Eastman’s cellulose-acetate textile brand. Product variants and recycled-content offerings should be distinguished.','Naia builds on cellulose-acetate chemistry with a contemporary branded textile range. A brand-level claim should be checked against the exact yarn or staple product.','https://naia.eastman.com/'],
 ['sorona','Sorona®','Partly bio-based polymer','polyester','A branded PTT polymer platform using a partly bio-based input route. It is not elastane and is not simply PET polyester under another name.','Sorona connects industrial biotechnology with polyester-family performance materials. Its brand programs cover particular apparel and carpet applications.','https://sorona.com/'],
 ['bemberg','Bemberg™','Cupro brand','cupro','Asahi Kasei’s cupro fiber brand, associated with regenerated cellulose from cotton linters.','Bemberg belongs to the history of cuprammonium cellulose and fine lining materials. The brand name identifies a producer’s product, while cupro names the fiber type.','https://www.asahi-kasei.com/fibers/en/bemberg/'],
 ['lycra','LYCRA®','Stretch-fiber brand','spandex','A familiar branded elastane offering within a wider technology portfolio. The word is often used loosely, so read the generic composition.','LYCRA became closely associated with stretch clothing. Its brand history follows the expansion of elastane into everyday apparel and technical fabric systems.','https://www.lycra.com/'],
 ['kevlar','Kevlar®','Para-aramid brand','para-aramid','A para-aramid product family used in engineered textile and composite applications. Whole-product testing determines protection.','Kevlar grew from high-performance polymer research at DuPont. The official brand destination now identifies Arclin; the generic fiber remains para-aramid.','https://www.arclin.com/kevlar/'],
 ['nomex','Nomex®','Meta-aramid brand','meta-aramid','A brand associated with heat-resistant meta-aramid materials and related product forms.','Nomex’s history connects polymer science with thermal-protection systems. Its official brand destination now identifies Arclin; fabric and garment specifications remain essential.','https://www.arclin.com/nomex/'],
 ['dyneema','Dyneema®','UHMWPE brand','polyethylene','A high-performance polyethylene product family. Fiber, fabric, laminate and rope constructions have different properties.','Dyneema developed around engineered polyethylene strength. Its textile applications extend from lightweight equipment to demanding technical systems.','https://www.dyneema.com/'],
 ['nuyarn','Nuyarn®','Yarn construction technology','wool','A proprietary yarn technology commonly associated with wool blends. It changes yarn construction rather than naming a new animal fiber.','Nuyarn’s story concerns how fibers are assembled into yarn. Evaluate the complete blend and tested fabric rather than transferring every brand claim to every garment.','https://nuyarn.com/'],
 ['zq','ZQ','Wool sourcing program','wool','A wool sourcing and assurance program, not a distinct species or generic fiber. Verify the applicable program scope for the product.','ZQ reflects the development of differentiated wool sourcing and grower relationships. Its name belongs in the provenance conversation alongside the underlying wool specification.','https://www.discoverzq.com/'],
 ['seacell','SeaCell™','Cellulose composite fiber','lyocell','A branded cellulose fiber incorporating seaweed material. It should not be described as a fabric made entirely from seaweed.','SeaCell is part of the development of functionalized cellulose fibers. Product formulation and evidence matter more than transferring general seaweed benefits to a textile.','https://smartfiber.de/en/seacell/'],
 ['coolmax','COOLMAX®','Performance-fiber technology','polyester','A performance brand associated with moisture-management fiber and fabric technologies. Exact polymer and recycled-content variants should be checked.','COOLMAX helped make engineered moisture management a familiar apparel claim. The actual effect depends on fiber geometry, yarn, fabric and garment design.','https://www.coolmax.com/'],
 ['wolf-vs-goat','Wolf vs Goat','Fabric-first apparel brand','wool','An apparel brand that publishes material education about merino micron, mill yarns and cloth construction. It is a reference brand for learning materials language, not a proprietary fiber.','Wolf vs Goat grew as a garment maker that names mill yarns and fiber grades in public product stories. Use those stories to practice separating mill yarn brands from fiber classes; they are attributed examples, not endorsements or proof of every batch.','https://www.wolfvsgoat.com/'],
];
export const brands=Object.fromEntries(rows.map(([id,name,type,base,composition,history,url])=>[id,{id,name,type,base,composition,history,family:'Brands & technologies',tagline:type+' · understand the name behind the label.',feel:'Depends on the specified fiber grade, yarn and fabric construction.',uses:'See the linked underlying material and the producer’s product-specific documentation.',care:'Follow the finished product’s care label. A trademark does not specify the care needs of every blend or construction.',tradeoff:'Producer claims apply to defined products and comparisons. This atlas does not independently certify performance, sourcing or environmental claims.',question:'Which exact grade, composition and current producer documentation apply to this product?',sources:['brand-'+id],referenceOnly:true,brand:true,url}]));
export const brandSources=rows.map(([id,name,type,base,composition,history,url])=>({id:'brand-'+id,name:name.replace(/[™®]/g,''),title:'Official product information',url,note:'Producer source for brand identity and claimed technology. Inclusion is not an endorsement.'}));
