// Editorial material profiles. Routes illustrate possible sequences, not tracked shipments.
export const sources = [
 {id:'woolmark',name:'The Woolmark Company',title:'Wool processing',url:'https://www.woolmark.com/industry/use-wool/wool-processing/',note:'Technical reference for scouring, carding, combing, spinning and fabric formation.'},
 {id:'flax',name:'Alliance for European Flax-Linen & Hemp',title:'All about European flax',url:'https://allianceflaxlinenhemp.eu/en/all-about-european-linen',note:'Industry reference for flax geography, fiber extraction and linen terminology.'},
 {id:'lenzing',name:'Lenzing',title:'Fiber production technologies',url:'https://www.lenzing.com/technology-production/technologies/',note:'Producer explanation of lyocell, viscose and modal. Its process claims describe its own operations.'},
 {id:'exchange',name:'Textile Exchange',title:'Materials Market Report 2025',url:'https://textileexchange.org/knowledge-center/reports/materials-market-report-2025/',note:'2024 global production data, published September 2025. This is a dated snapshot, not a live counter.'},
 {id:'standards',name:'Textile Exchange',title:'Material standards',url:'https://textileexchange.org/standards/',note:'Official entry point for scope, claims and current versions of material standards.'},
 {id:'sfa',name:'Sustainable Fibre Alliance',title:'Standards and resources',url:'https://sustainablefibre.org/resources/',note:'Cashmere sourcing, primary processing and chain-of-custody reference.'},
 {id:'fao',name:'Food and Agriculture Organization',title:'Harvesting of textile animal fibres',url:'https://www.fao.org/4/v9384e/v9384e00.htm',note:'Historical technical reference. Not used as a source of current market shares or trade flows.'},
 {id:'jute',name:'Food and Agriculture Organization',title:'Jute and hard fibres',url:'https://www.fao.org/markets-and-trade/commodities-overview/fibres/jute-and-hard-fibres/',note:'Commodity background and end-use reference.'},
 {id:'ramie',name:'Food and Agriculture Organization',title:'Boehmeria nivea crop profile',url:'https://ecocrop.apps.fao.org/ecocrop/srv/en/cropView?id=3746',note:'Botanical and agricultural reference for ramie.'},
 {id:'qiviut',name:'Musk Ox Farm',title:'Qiviut in Palmer, Alaska',url:'https://www.muskoxfarm.org/',note:'A specific example of musk ox husbandry and hand-combed qiviut, not proof of every Arctic route.'},
 {id:'cites',name:'CITES',title:'Vicuña and international trade',url:'https://cites.org/eng',note:'Consult current species listings and national authorities for actual trade requirements.'},
 {id:'map',name:'Natural Earth / World Atlas',title:'World map geometry',url:'https://github.com/topojson/world-atlas',note:'Bundled generalized map data. City markers are approximate and do not identify suppliers.'}
];
// name, family, descriptor, composition, feel, uses, care, tradeoff, question, source IDs
const entries = {
 wool:['Merino wool','Animal','From open pasture to considered cloth.','Keratin from sheep fleece. Merino describes a sheep breed and its wool, rather than a fabric construction.','Springy, insulating, with a soft hand in finer grades.','Knitwear, tailoring, base layers and blankets.','Follow the label. Air between wears; use a wool cycle only if permitted, avoid agitation and dry knitwear flat.','Farming, land management, processing energy and garment longevity all matter. A natural origin alone is not an impact assessment.','Can the seller identify the wool origin, mill, fiber grade and scope of any animal-welfare certification?',['woolmark','standards']],
 cashmere:['Cashmere','Animal','A winter undercoat, a long spring journey.','The fine undercoat of cashmere goats, separated from coarser guard hairs.','Soft and lofty, with warmth at a relatively light weight.','Sweaters, scarves, lightweight coating and accessories.','Wash only as the care label allows. Minimize rubbing, reshape gently and dry flat. Remove pills carefully.','Rangeland condition, herd management and dehairing practices deserve attention alongside the finished hand.','What evidence connects this garment to its herding region and processing chain?',['sfa','fao']],
 linen:['Linen','Plant','A field of flax, woven into summer.','Bast fiber extracted from flax stems. Linen is the textile fiber name; flax is the plant.','Crisp, absorbent and characteristically creased; softens with use.','Shirting, summer tailoring, table linen and bedding.','Follow the label, allow space in the wash and reshape while damp. Creasing is part of its character.','Cultivation conditions and retting methods vary. Dyeing, finishing and fabric construction also shape the final footprint.','Where was the flax grown, and where were spinning, weaving and finishing performed?',['flax']],
 cotton:['Cotton','Plant','A seed fiber with a world of possibilities.','Cellulose hairs growing around the seeds of the cotton plant, separated at ginning.','Absorbent and versatile; the feel depends strongly on yarn and weave.','T-shirts, denim, shirts, towels and bedding.','Follow the care label and separate colors. Excess heat can shrink some cotton fabrics and weaken finishes.','Irrigation needs depend on place and season. Farming inputs, labor conditions and wet processing need specific evidence.','Which growing region and chain-of-custody evidence support the cotton claim?',['exchange','standards']],
 silk:['Silk','Animal','A continuous filament, a luminous cloth.','Protein filament formed by silkworms in cocoons. Cultivated mulberry silk is one important type.','Smooth with characteristic luster and fluid drape.','Scarves, dresses, ties, linings and decorative textiles.','Check the label before washing. Avoid wringing, harsh detergents and prolonged direct sun; test colorfastness.','Sericulture, cocoon processing and finishing practices vary. Silk does not imply a single animal-welfare method.','Is the producer able to explain the silk type, cocoon process and dyeing location?',['fao']],
 alpaca:['Alpaca','Animal','The Andes, carried in a fleece.','Hair from alpacas. Huacaya and Suri fleeces have different structures and textile effects.','Warm with a soft or silky handle depending on grade and construction.','Knitwear, scarves, blankets and coating fabrics.','Use the garment label, support wet knits and dry flat. Store clean and protect from textile pests.','Fiber grading and sorting matter as much as origin. Animal care and producer livelihoods need separate attention.','What grade was used, and how are farms and processors identified?',['fao','standards']],
 mohair:['Mohair','Animal','Luster from the Angora goat.','Hair from Angora goats. It is different from angora rabbit fiber.','Lustrous, resilient and sometimes intentionally fuzzy.','Tailoring blends, airy knits, upholstery and pile fabrics.','Handle brushed surfaces gently. Follow the label, limit friction and avoid stretching wet knitwear.','Age and grade influence handle. Farm welfare, grazing practices and finishing are relevant sourcing questions.','Is the mohair origin documented, and does any certification cover this product?',['fao','standards']],
 yak:['Yak down','Animal','A fine underlayer from the high plateau.','The fine insulating undercoat of yaks, separated from coarser outer hair.','Soft, warm and often used in natural brown tones.','Knitwear, scarves, blankets and wool blends.','Follow the label and treat fine down knits gently. Reshape and dry flat rather than hanging.','Collection methods, dehairing yield and herder compensation vary. Scarcity alone does not demonstrate responsible production.','Who collected the down, and how was it separated, graded and purchased?',['fao']],
 angora:['Angora','Animal','Rabbit down with a distinctive halo.','Fine hair from Angora rabbits, often blended with other fibers for practical yarns.','Very fluffy, light and warm; can shed during wear.','Halo-effect knitwear, accessories and blended yarns.','Limit rubbing and follow the care label. Store folded; use gentle handling to preserve the surface.','Harvesting method and animal welfare are central. A country label does not establish humane handling.','Can the brand substantiate the farm conditions and collection method?',['fao']],
 vicuna:['Vicuña','Animal','A rare Andean down with a complex provenance.','Fine undercoat from the wild vicuña, an Andean camelid.','Exceptionally fine handle; typically used in delicate luxury cloth.','Scarves, shawls, fine knitwear and coating.','Follow specialist care instructions. Protect from abrasion and store clean with suitable pest prevention.','Rarity increases the importance of documented origin, community benefit and lawful sourcing.','Can the seller provide origin and trade documentation appropriate to the specific product?',['fao','cites']],
 camel:['Camel hair','Animal','Warmth gathered from a seasonal coat.','Fine down from the camel coat, separated from coarse hair; Bactrian camel is a familiar source.','Soft warmth and a characteristic natural tan palette.','Coats, knitwear, scarves and blankets.','Follow the label, brush coats gently and give garments time to air between wears.','Collection, dehairing and blending affect quality. The color name camel does not guarantee camel-fiber content.','Does the composition actually include camel hair, and in what proportion?',['fao']],
 guanaco:['Guanaco','Animal','A Patagonian fiber with a conservation story.','Fine undercoat from the guanaco, a South American camelid.','Fine and warm, with a limited specialty market.','Fine scarves, knitwear and specialty cloth.','Follow specialist instructions; protect fine cloth from abrasion and moth damage.','Origin and collection require close scrutiny. The atlas retains geographic concepts without validating a commercial chain.','Is there independent documentation of the origin and collection method?',['fao','cites']],
 qiviut:['Qiviut','Animal','An Arctic undercoat, patiently gathered.','The soft underwool of the musk ox, shed seasonally.','Light, soft and insulating, often used in small accessories.','Lace scarves, cowls, hats and hand-knitting yarn.','Follow the maker’s directions. Treat lace structures gently and support the fabric when wet.','Farm-combed and other collection channels differ. Know the maker and the origin rather than relying on broad warmth claims.','Who gathered and processed the qiviut, and where was the piece made?',['qiviut']],
 hemp:['Hemp','Plant','A strong stem fiber, made wearable.','Bast fiber from hemp stems; processing can retain long fibers or create shorter cottonized fibers.','Textured and firm in some fabrics, much softer in fine yarns or blends.','Shirting, denim blends, canvas and home textiles.','Follow the label. Wash with similar colors and avoid excessive drying heat.','Retting, separation and softening determine much of the processing burden. Hemp is not automatically chemical-free.','Was it mechanically processed or cottonized, and what share is actually hemp?',['flax','jute']],
 jute:['Jute','Plant','The golden fiber of working textiles.','Bast fiber from Corchorus plants, separated from the stem.','Coarse and textured, suited to structure rather than soft next-to-skin use.','Sacking, rugs, cordage, geotextiles and composites.','Keep dry and follow item-specific guidance. Wet cleaning can distort or discolor some jute goods.','Retting water, mill conditions and product treatments influence the material’s practical impact.','What is the intended lifetime, and are coatings or backing materials disclosed?',['jute']],
 polyester:['Polyester','Synthetic','Engineered filaments, everywhere around us.','For most apparel, polyethylene terephthalate (PET), formed into continuous filament or staple fiber.','Versatile, low in moisture absorption and often quick to dry.','Sportswear, fleece, linings, home textiles and blends.','Follow the label, avoid unnecessary heat and wash only as needed. Reduce avoidable abrasion.','Virgin fossil feedstock, energy use and microfiber shedding are key considerations. Recycled content does not eliminate shedding.','What is the feedstock, recycled percentage and evidence for any recycling claim?',['exchange','standards']],
 nylon:['Nylon','Synthetic','Strength designed into a filament.','A family of polyamides, commonly nylon 6 or nylon 6,6 in textiles.','Strong, smooth and abrasion-resistant, with properties that vary by polymer and yarn.','Hosiery, outerwear, swimwear, luggage and technical fabrics.','Follow the label and avoid high heat. Coatings and elastane blends may need special care.','Polymer type affects recycling options. Durability claims should be matched to the actual fabric and use.','Which polyamide is used, and is a realistic take-back or recycling route available?',['exchange']],
 spandex:['Elastane','Synthetic','A little stretch changes the whole garment.','A segmented polyurethane fiber, also known as spandex, typically used in blends.','Highly extensible, adding recovery rather than bulk.','Stretch denim, sportswear, underwear and swimwear.','Avoid high heat unless permitted. Follow the label; chlorine, heat and time can reduce elastic recovery.','Small percentages can improve fit and wear but complicate separation and recycling of blended textiles.','How much elastane is necessary, and is recovery maintained through repeated use?',['exchange']],
 acrylic:['Acrylic','Synthetic','A spun staple with a wool-like hand.','A synthetic fiber based primarily on acrylonitrile, usually spun into staple yarn.','Light and bulky, often with a soft, wool-like texture.','Sweaters, blankets, craft yarn and upholstery blends.','Follow the label. Avoid excess heat and handle pills carefully rather than pulling them off.','Fossil feedstock, process chemistry, pilling and synthetic-fiber shedding all merit consideration.','How does the fabric perform after washing, and what lifetime is expected?',['exchange']],
 viscose:['Viscose','Cellulosic','Plant cellulose, dissolved and remade.','Regenerated cellulose made from dissolving pulp through the viscose process; often called rayon.','Absorbent with fluid drape; wet strength varies by fiber type.','Dresses, blouses, linings and knit blends.','Follow the label, support wet fabric and avoid wringing. Some garments require professional cleaning.','Wood sourcing and chemical recovery are separate questions. Plant feedstock does not make every process equivalent.','Can the supplier identify the pulp source and the fiber producer?',['lenzing']],
 lyocell:['Lyocell','Cellulosic','Cellulose transformed through a solvent process.','Regenerated cellulose produced by direct solvent dissolution, distinct from the viscose process.','Smooth and absorbent, with drape shaped by yarn and finishing.','Shirting, denim blends, dresses and bedding.','Follow the care label and wash gently where allowed. Surface fibrillation can change the appearance of some fabrics.','Solvent recovery, energy supply and pulp origin differ among producers. Brand-specific claims should not be generalized.','Which producer made the fiber, and what recovery and forest-sourcing claims are verified?',['lenzing']],
 modal:['Modal','Cellulosic','Regenerated cellulose with wet strength in mind.','A modified viscose-type cellulose fiber with improved wet mechanical properties.','Soft, absorbent and often used in smooth jersey.','Underwear, loungewear, T-shirts and bedding blends.','Use the label’s wash and dry instructions. Support delicate knits and avoid unnecessary heat.','The process and wood supply need documentation. Modal is a generic fiber name, not one exclusive brand.','Which fiber producer and pulp sources stand behind the material?',['lenzing']],
 ramie:['Ramie','Plant','An old bast fiber with a bright surface.','Bast fiber from Boehmeria nivea, a perennial plant also called China grass.','Lustrous and relatively crisp, often blended for handling and drape.','Summer shirts, woven textiles and blends.','Follow the label and reshape when damp. Blends and finishes determine suitable ironing and washing.','Separating and degumming the fiber is important to textile performance and processing impact.','How was the fiber degummed, and what other fibers are in the fabric?',['ramie']],
 'recycled-wool':['Recycled wool','Recycled','Another life for an existing thread.','Wool recovered from production waste or used textiles, sorted and mechanically opened.','Varies with the input; often blended to balance shorter recovered fibers.','Coats, blankets, knitwear and felted products.','Care for the whole blend according to the label. Air between wears and repair small damage early.','Recovered fibers can be shorter. Input quality, blend share and new dyeing determine the result.','Is the input pre-consumer or post-consumer, and what percentage is recycled?',['standards','woolmark']],
 'recycled-polyester':['Recycled polyester','Recycled','A new filament from an existing polymer.','PET reprocessed from sources such as bottles, industrial waste or textiles.','Can provide similar textile functions to virgin polyester; quality depends on feedstock and processing.','Fleece, sportswear, linings, bags and home textiles.','Follow the label, reduce avoidable heat and friction, and repair rather than replace where practical.','Bottle-to-fiber recycling is not the same as textile-to-textile recycling. Microfiber shedding remains relevant.','What waste stream supplied the PET, and is the recycled fraction independently verified?',['exchange','standards']],
 mink:['Mink','Specialty','An archival view of a pelt-based material.','Mink is usually traded as a fur pelt, not as a conventional spun apparel fiber.','A dense underfur and visible guard-hair surface.','Fur garments, panels and trim.','Use a specialist familiar with the material and construction; avoid improvised washing.','Animal welfare and traceability are central. Original map connections are retained as unverified legacy concepts.','Can the seller document the species, provenance and handling at every stage?',['fao']],
 fox:['Fox fur','Specialty','A pelt material with a pronounced pile.','Usually a fur pelt rather than a conventional textile fiber; species and product form need identification.','Long visible hairs over a denser underfur.','Fur panels, trim and specialty products.','Seek item-specific specialist care. Protect from heat and compression.','A geographic map cannot substantiate animal welfare or the origin of a pelt. Legacy connections remain unverified.','Is the exact species and supply chain disclosed with supporting records?',['fao']],
 tanuki:['Raccoon dog fur','Specialty','A species name matters as much as a trade name.','Fur from a raccoon dog, sometimes sold under the name tanuki. It is not raccoon fiber.','A long-haired fur surface used as a pelt or trim.','Trim and fur products.','Use item-specific specialist care and avoid heat or improvised cleaning.','The legacy atlas’s trade links have not been independently verified. Species identification and welfare evidence are essential.','Does the product disclose the species accurately and support the provenance claim?',['fao']],
 yangir:['Yangir','Specialty','A rare trade name that needs careful evidence.','A specialty trade term associated with ibex down. Exact species and collection claims require supplier evidence.','Reported as a fine specialty down; no standardized performance ranking is asserted here.','Specialty luxury yarns and cloth.','Follow the maker’s fiber-specific instructions and protect delicate cloth from abrasion.','Publicly verifiable route information is limited. Original Altai-to-Italy links are research leads, not established transactions.','What independently checkable evidence supports the species, collection and provenance?',['fao']],
 cervelt:['Cervelt','Specialty','A proprietary name in the rare-fiber archive.','A trade name associated with red-deer down from New Zealand. Supplier-specific specifications require verification.','Marketed as a fine down; this atlas does not independently validate performance claims.','Specialty luxury knitwear and accessories.','Use the maker’s instructions rather than assuming standard wool care applies.','The original geographic model is retained for context. Commercial volumes, current mills and performance need primary evidence.','Can the maker provide specifications and documented origin for this exact product?',['fao']]
};
export const profiles=Object.fromEntries(Object.entries(entries).map(([id,v])=>[id,{id,name:v[0],family:v[1],tagline:v[2],composition:v[3],feel:v[4],uses:v[5],care:v[6],tradeoff:v[7],question:v[8],sources:v[9],legacyOnly:v[1]==='Specialty'}]));
export const articles=[
 {id:'read-the-label',tag:'START HERE',title:'A label is a beginning. Follow the rest of the story.',dek:'Five questions that take you beyond a fiber percentage.',time:4,fibers:['wool','cotton','viscose'],sources:['standards','sfa'],sections:[['Start with composition','Read every component, including linings and any elastane. A fabric called a wool coat can include a blend, a synthetic lining and interfacing. Record the stated percentages before comparing products.'],['Separate origin from manufacture','The country where a garment was assembled may be different from the places where its fiber was grown, spun and woven. Ask for those stages separately. A mill name is useful only if you know what that mill actually did.'],['Ask for evidence that matches the claim','A farm-level claim, a chemical-testing claim and a recycled-content claim answer different questions. Ask whether the claim applies to the specific product, and whether a current certificate or transaction record supports it.'],['Look at the cloth in front of you','Handle, seams, weight, recovery and fit affect whether a garment will be worn for years. Fiber names can help frame questions; they cannot replace inspection of a finished piece.'],['Use the care label as a design clue','A material may sound easy to wash while its lining, dye or finish demands something different. The whole garment’s instructions should govern care.']]},
]