export const regions=[
 {id:'oceania',name:'Oceania',subtitle:'Pasture, fleece & first connections',countries:['Australia','New Zealand'],intro:'Start with the pastoral landscapes of Australia and New Zealand. The atlas links wool collection areas to processing hubs abroad, while the specialty archive keeps a separate record of the original deer-down concept.',question:'Which farm region, classing records and exporter connect the raw material to the mill?',color:'#a7b49a'},
 {id:'andes',name:'The Andes & Patagonia',subtitle:'Altitude, camelids & local knowledge',countries:['Peru','Bolivia','Chile','Argentina','Uruguay'],intro:'Alpaca, vicuña and guanaco bring very different collection and provenance questions. Arequipa is a focal point in the atlas’s Andean textile model; southern wool origins add another set of connections.',question:'How are collection, sorting, community benefit and origin documented?',color:'#b78c6e'},
 {id:'east-asia',name:'East Asia',subtitle:'From herding country to industrial scale',countries:['China','Mongolia','South Korea','Japan'],intro:'The region spans pastoral origins, polymer production, spinning, weaving and retail. Similar geographic paths can carry entirely different material forms, from unprocessed down to finished garments.',question:'At each border, is the product raw fiber, top, yarn, fabric or a finished garment?',color:'#9fae91'},
 {id:'south-asia',name:'South Asia',subtitle:'Cotton, jute & the making of garments',countries:['India','Bangladesh','Nepal','Afghanistan'],intro:'Explore cotton spinning, jute processing, garment production and specialty wool routes. The atlas uses regional centers to make these stages legible without implying that all facilities share the same practices.',question:'Which specific spinning, wet-processing and garment facilities handled the order?',color:'#c5ae78'},
 {id:'europe',name:'Europe',subtitle:'Flax fields, mill towns & material science',countries:['Italy','France','Belgium','Lithuania','Austria','United Kingdom','Germany','Finland','Poland','Denmark','Greece','Turkey'],intro:'European nodes include flax cultivation, wool and silk textile districts, regenerated cellulose and recycled-wool processing. A European finishing location does not, by itself, describe the origin of the fiber.',question:'Which stages were performed locally, and which raw or intermediate materials were imported?',color:'#89a298'},
 {id:'africa',name:'Africa',subtitle:'Wool, mohair & cellulose feedstocks',countries:['South Africa','Lesotho','Mali'],intro:'The atlas connects southern African animal fibers with processing hubs and places West African cotton and southern African pulp into separate material stories. These are distinct industries with different evidence needs.',question:'What farm, collection and processing records accompany the material?',color:'#b69b7a'},
 {id:'americas',name:'North America & the Arctic',subtitle:'Cotton fields and northern underwool',countries:['United States','Canada','Greenland'],intro:'Cotton, technical fibers and qiviut sit far apart in both scale and geography. The model makes those contrasts visible while retaining the difference between a named producer example and a hypothetical downstream route.',question:'Is the geographic claim tied to a specific producer or only to a broad regional association?',color:'#a1abb3'},
 {id:'other-origins',name:'Other global connections',subtitle:'Pulp, feedstocks & markets',countries:['Brazil','Saudi Arabia','United Arab Emirates','Vietnam','Thailand','Indonesia'],intro:'Feedstocks and intermediate materials connect distant industries. Brazilian pulp, petrochemical inputs and Asian garment stages illustrate why the final place on a label tells only part of a textile story.',question:'What intermediate product is moving, and what evidence supports the proposed link?',color:'#b7a79a'}
];
