// Editorial material profiles. Routes illustrate possible sequences, not tracked shipments.
export const sources = [
 {id:'woolmark',name:'The Woolmark Company',title:'Wool processing',url:'https://www.woolmark.com/industry/use-wool/wool-processing/',note:'Technical reference for scouring, carding, combing, spinning and fabric formation.'},
 {id:'flax',name:'Alliance for European Flax-Linen & Hemp',title:'All about European flax',url:'https://allianceflaxlinenhemp.eu/en/all-about-european-linen',note:'Industry reference for flax geography, fiber extraction and linen terminology.'},
 {id:'lenzing',name:'Lenzing',title:'Fiber production technologies',url:'https://www.lenzing.com/technology-production/technologies/',note:'Producer explanation of lyocell, viscose and modal. Its process claims describe its own operations.'},
 {id:'exchange',name:'Textile Exchange',title:'Materials Market Report 2025',url:'https://textileexchange.org/knowledge-center/reports/materials-market-report-2025/',note:'2024 global production data, published September 2025. This is a dated snapshot, not a live counter.'},
 {id:'standards',name:'Textile Exchange',title:'Material standards',url:'https://textileexchange.org/standards/',note:'Official entry point for scope, claims and current versions of material standards.'},
 {id:'sfa',name:'Sustainable Fibre Alliance',title:'Standards and resources',url:'https://sustainablefibre.org/resources/',note:'Cashmere sourcing, primary processing and chain-of-custody reference.'},
 {id:'fao',name:'Food and Agriculture Organization',title:'Harvesting of textile animal fibres',url:'https://www.fao.org/4/v9384e/v9384e00.htm',note:'Historical technical reference. Not used as a source of current market shares or trade flows.'},
 {id:'jute',name:'Food and Agriculture Organization',title:'Jute and hard fibres',url:'https://www.fao.org/markets-and-trade/commodities-overview/fibres/jute-and-hard-fibres/',note:'Commodity background and end-use reference.'},
 {id:'ramie',name:'Food and Agriculture Organization',title:'Boehmeria nivea crop profile',url:'https://ecocrop.apps.fao.org/ecocrop/srv/en/cropView?id=3746',note:'Botanical and agricultural reference for ramie.'},
 {id:'qiviut',name:'Musk Ox Farm',title:'Qiviut in Palmer, Alaska',url:'https://www.muskoxfarm.org/',note:'A specific example of musk ox husbandry and hand-combed qiviut, not proof of every Arctic route.'},
 {id:'cites',name:'CITES',title:'Vicuña and international trade',url:'https://cites.org/eng',note:'Consult current species listings and national authorities for actual trade requirements.'},
 {id:'map',name:'Natural Earth / World Atlas',title:'World map geometry',url:'https://github.com/topojson/world-atlas',note:'Bundled generalized map data. City markers are approximate and do not identify suppliers.'}
];
// name, family, descriptor, composition, feel, uses, care, tradeoff, question, source IDs
const entries = {
 wool:['Merino wool','Animal','From open pasture to considered cloth.','Keratin from sheep fleece. Merino describes a sheep breed and its wool, rather than a fabric construction.','Springy, insulating, with a soft hand in finer grades.','Knitwear, tailoring, base layers and blankets.','Follow the label. Air between wears; use a wool cycle only if permitted, avoid agitation and dry knitwear flat.','Farming, land management, processing energy and garment longevity all matter. A natural origin alone is not an impact assessment.','Can the seller identify the wool origin, mill, fiber grade and scope of any animal-welfare certification?',['woolmark','standards']],
 cashmere:['Cashmere','Animal','A winter undercoat, a long spring journey.','The fine undercoat of cashmere goats, separated from coarser guard hairs.','Soft and lofty, with warmth at a relatively light weight.','Sweaters, scarves, lightweight coating and accessories.','Wash only as the care label allows. Minimize rubbing, reshape gently and dry flat. Remove pills carefully.','Rangeland condition, herd management and dehairing practices deserve attention alongside the finished hand.','What evidence connects this garment to its herding region and processing chain?',['sfa','fao']],
 linen:['Linen','Plant','A field of flax, woven into summer.','Bast fiber extracted from flax stems. Linen is the textile fiber name; flax is the plant.','Crisp, absorbent and characteristically creased; softens with use.','Shirting, summer tailoring, table linen and bedding.','Follow the label, allow space in the wash and reshape while damp. Creasing is part of its character.','Cultivation conditions and retting methods vary. Dyeing, finishing and fabric construction also shape the final footprint.','Where was the flax grown, and where were spinning, weaving and finishing performed?',['flax']],
 cotton:['Cotton','Plant','A seed fiber with a world of possibilities.','Cellulose hairs growing around the seeds of the cotton plant, separated at ginning.','Absorbent and versatile; the feel depends strongly on yarn and weave.','T-shirts, denim, shirts, towels and bedding.','Follow the care label and separate colors. Excess heat can shrink some cotton fabrics and weaken finishes.','Irrigation needs depend on place and season. Farming inputs, labor conditions and wet processing need specific evidence.','Which growing region and chain-of-custody evidence support the cotton claim?',['exchange','standards']],
 silk:['Silk','Animal','A continuous filament, a luminous cloth.','Protein filament formed by silkworms in cocoons. Cultivated mulberry silk is one important type.','Smooth with characteristic luster and fluid drape.','Scarves, dresses, ties, linings and decorative textiles.','Check the label before washing. Avoid wringing, harsh detergents and prolonged direct sun; test colorfastness.','Sericulture, cocoon processing and finishing practices vary. Silk does not imply a single animal-welfare method.','Is the producer able to explain the silk type, cocoon process and dyeing location?',['fao']],
 alpaca:['Alpaca','Animal','The Andes, carried in a fleece.','Hair from alpacas. Huacaya and Suri fleeces have different structures and textile effects.','Warm with a soft or silky handle depending on grade and construction.','Knitwear, scarves, blankets and coating fabrics.','Use the garment label, support wet knits and dry flat. Store clean and protect from textile pests.','Fiber grading and sorting matter as much as origin. Animal care and producer livelihoods need separate attention.','What grade was used, and how are farms and processors identified?',['fao','standards']],
 mohair:['Mohair','Animal','Luster from the Angora goat.','Hair from Angora goats. It is different from angora rabbit fiber.','Lustrous, resilient and sometimes intentionally fuzzy.','Tailoring blends, airy knits, upholstery and pile fabrics.','Handle brushed surfaces gently. Follow the label, limit friction and avoid stretching wet knitwear.','Age and grade influence handle. Farm welfare, grazing practices and finishing are relevant sourcing questions.','Is the mohair origin documented, and does any certification cover this product?',['fao','standards']],
 yak:['Yak down','Animal','A fine underlayer from the high plateau.','The fine insulating undercoat of yaks, separated from coarser outer hair.','Soft, warm and often used in natural brown tones.','Knitwear, scarves, blankets and wool blends.','Follow the label and treat fine down knits gently. Reshape and dry flat rather than hanging.','Collection methods, dehairing yield and herder compensation vary. Scarcity alone does not demonstrate responsible production.','Who collected the down, and how was it separated, graded and purchased?',['fao']],
 angora:['Angora','Animal','Rabbit down with a distinctive halo.','Fine hair from Angora rabbits, often blended with other fibers for practical yarns.','Very fluffy, light and warm; can shed during wear.','Halo-effect knitwear, accessories and blended yarns.','Limit rubbing and follow the care label. Store folded; use gentle handling to preserve the surface.','Harvesting method and animal welfare are central. A country label does not establish humane handling.','Can the brand substantiate the farm conditions and collection method?',['fao']],
 vicuna:['Vicuña','Animal','A rare Andean down with a complex provenance.','Fine undercoat from the wild vicuña, an Andean camelid.','Exceptionally fine handle; typically used in delicate luxury cloth.','Scarves, shawls, fine knitwear and coating.','Follow specialist care instructions. Protect from abrasion and store clean with suitable pest prevention.','Rarity increases the importance of documented origin, community benefit and lawful sourcing.','Can the seller provide origin and trade documentation appropriate to the specific product?',['fao','cites']],
