import {glossary as definitions} from './content.js';
import extension from './data/glossary-extended.js';
const {additions:glossaryAdditions,depth:glossaryDepth}=extension;
import {createIndex} from './search.js';
export const reviewed='2026-09-22';
const cw=(slug,title)=>({title:'CottonWorks: '+title,url:'https://cottonworks.com/encyclopedia-item/'+slug+'/'});
export const glossarySources={
 card:cw('carding','Carding'),comb:cw('combing','Combing'),denier:cw('denier','Denier'),hand:cw('hand','Hand'),knit:cw('knitting','Knitting'),dye:cw('dyeing','Dyeing'),finish:cw('finishing','Finishing'),sliver:cw('sliver','Sliver'),staple:cw('staple-yarn','Staple yarn'),weave:cw('weaving','Weaving'),pill:cw('pilling','Pilling'),
 flax:{title:'Alliance for European Flax-Linen & Hemp: Flax growing and expertise',url:'https://allianceflaxlinenhemp.eu/en/flax-growing-expertise'},
 hemp:{title:'Alliance for European Flax-Linen & Hemp: Textile applications of hemp',url:'https://allianceflaxlinenhemp.eu/en/textile-applications-hemp'},
 flaxmap:{title:'Alliance: Mapping of processes for European flax-linen',url:'https://allianceflaxlinenhemp.eu/en/document_resources/13/download'},
 cashmere:{title:'Cashmere and Camel Hair Manufacturers Institute: Fiber definitions',url:'https://cashmere.org/definition-cashmere-wool.php'},
 scour:{title:'Woolmark: Scouring and carbonising',url:'https://www.woolmark.com/industry/product-development/wool-processing/woollen-scouring-carbonising/'},
 top:{title:'Woolmark: Worsted top-making',url:'https://www.woolmark.com/industry/product-development/wool-processing/worsted-top-making/'},
 wool:{title:'Woolmark: Wool processing',url:'https://www.woolmark.com/industry/use-wool/wool-processing/'},
 iwto:{title:'International Wool Textile Organisation: First-stage processing',url:'https://iwto.org/wool-supply-chain/first-stage-processing/'},
 micron:{title:'Woolmark: What is the wool fibre?',url:'https://www.woolmark.com/fibre/what-is-the-wool-fibre/'},
 pillcare:{title:'Woolmark: Pilling care factsheet',url:'https://www.woolmark.com/globalassets/_06-new-woolmark/_industry/certification/licensee-portal/gd5407-wool-care-factsheet_pilling.pdf'},
 lycra:{title:'The LYCRA Company: About LYCRA fiber',url:'https://one.lycra.com/en/lycra-frequently-asked-questions/about-lycra-fiber-website'},
 bisfa:{title:'BISFA: Terminology of man-made fibres (2017)',url:'https://bisfa.org/wp-content/uploads/2018/06/2017-BISFA-Terminology-final.pdf'},
 lenzing:{title:'Lenzing: Fiber production technologies',url:'https://www.lenzing.com/technology-production/technologies/'},
 gin:{title:'CottonWorks: Cotton growth, harvesting and ginning',url:'https://cottonworks.com/fiber/fiber-science/cotton-fiber-growth-harvesting-and-ginning/'},
 weavebasics:{title:'CottonWorks: Weaving basics',url:'https://cottonworks.com/learning-hub/weaving/weaving-basics/'},
 custody:{title:'Textile Exchange: Supply-chain certification',url:'https://textileexchange.org/get-certified/supply-chain/'},
 toolkit:{title:'Textile Exchange: Brand and retailer certification toolkit (2020)',url:'https://textileexchange.org/app/uploads/2022/11/TE-402-V1.0-Brand-and-Retailer-Certification-Toolkit.pdf'},
 policies:{title:'Textile Exchange: Standards policy and resource updates',url:'https://hub.textileexchange.org/home/site-wide-content/standards-policy-updates'},
 drape:{title:'NC State: Kawabata Evaluation System',url:'https://textiles.ncsu.edu/tpacc/comfort-performance/kawabata-evaluation-system/'},
 weights:{title:'Craft Yarn Council: Standard Yarn Weight System',url:'https://media.craftyarncouncil.com/standards/yarn-weight-system'}
};
// Original explanations and illustrative examples. References support the technical basis;
// examples are teaching scenarios, not evidence about a particular product.
const rows=[
['Bast fiber','Fiber structure','bast fibres, stem fiber',
'Bast describes where a fiber occurs in a plant. Flax and hemp provide bundles of strong supporting fibers in their stems. Processing separates those bundles from surrounding tissue and woody material before preparing them for yarn. A textile strand may still contain several associated cells, so a visible strand is not necessarily one elementary fiber.',
'A linen shirt starts with a stem-derived fiber; a cotton shirt starts with seed hairs. Both contain cellulose, but their extraction and preparation routes differ. This distinction helps explain why a flax journey includes retting and scutching while a cotton journey includes ginning.',
'Bast is a botanical category, not a guarantee of softness, organic cultivation or low impact. Ask which plant, preparation method and finished construction the description refers to.',['Retting','Scutching','Cottonization'],['flax','hemp']],
['Carding','Processing','carded, carded cotton',
'Carding opens a mass of fibers, separates tangles and produces a more manageable arrangement for later processing. Wire-covered surfaces help distribute the fibers; the output may be a web or a sliver, depending on the production system. Carding is a preparation step rather than the operation that makes a finished, twisted yarn.',
'Two cotton yarns can both be carded, while only one receives an additional combing step. On a mill specification, “carded” therefore describes preparation. It does not tell you the yarn count, twist, fabric weight or how the finished garment will feel after washing.',
'Do not treat carded as synonymous with low quality. The appropriate preparation depends on the intended yarn and fabric. Compare the actual finished textile and its performance requirements.',['Combing','Sliver','Worsted'],['card','wool']],
['Chain of custody','Claims & sourcing','CoC, certified supply chain',
'A chain-of-custody system connects a material claim to records and controls as goods pass between organizations. Under Textile Exchange certification, relevant supply-chain participants and transaction documentation help maintain the claimed material content through processing and trade. The exact rules depend on the standard and its current version.',
'Imagine a spinner buying certified recycled fiber. Evidence needs to connect the incoming material, processing records and outgoing yarn claim. A supplier’s general certificate and documentation for a particular shipment answer different questions. Request evidence that matches the goods you are evaluating.',
'A certification logo is not a complete account of every environmental or labor issue. Read its scope. Chain of custody supports specified claims; it should not be expanded into unrelated guarantees.',['Traceability','Pre-consumer','Post-consumer'],['custody']],
['Combing','Processing','combed cotton, combed wool, noil',
'Combing selects and prepares a fiber population after earlier opening and carding. It removes shorter fibers and helps arrange the retained fibers for subsequent yarn production. In wool processing it also removes neps and residual vegetable matter. The shorter material removed during wool combing is called noil and may enter other textile routes.',
'A combed cotton shirt and a carded cotton shirt can share the same fiber composition but use different yarn preparation. Compare their surface, construction and washing behavior rather than assuming that the extra processing step determines every aspect of quality.',
'Combing is not the same as shearing or dehairing. It primarily prepares textile fibers for spinning; dehairing separates the coarse and fine components of certain animal coats.',['Carding','Top','Dehairing'],['comb','top']],
['Cottonization','Processing','cottonisation, cottonized hemp, cottonised flax',
'Cottonization adapts bast fibers to shorter-staple processing systems. The route can involve opening, shortening and refining fiber bundles, using mechanical and sometimes wet-processing steps. Its purpose is compatibility with equipment and blends, rather than changing the plant species or turning hemp or flax into cotton.',
'A spinner might blend cottonized hemp with cotton to use an established short-staple production line. The resulting yarn still contains hemp. The blend ratio, remaining bundle size and processing conditions help determine its suitability for the planned fabric.',
'Cottonized is a process description, not a fiber-content claim. It also differs from regenerated cellulose, where cellulose is dissolved and formed into a new fiber. Ask for the actual composition and preparation route.',['Bast fiber','Staple','Regenerated cellulose'],['hemp','flaxmap']],
['Dehairing','Processing','dehaired, undercoat separation',
'Dehairing separates the fine undercoat sought for textiles from the coarser outer hairs present in some animal fleeces. Cashmere is associated with the fine, dehaired undercoat of the cashmere goat. Separation matters because an average description of a fleece can conceal very different fiber populations.',
'When discussing a cashmere lot, ask whether measurements describe the raw mixed fleece or the prepared textile fiber. A soft-looking photograph cannot establish how effectively coarse hairs were removed. Composition and diameter information provide different pieces of evidence.',
'Dehairing is not simply another name for washing, nor does it mean that every remaining fiber has an identical diameter. Avoid judging finished comfort from a process name alone; yarn construction and surface finishing also matter.',['Guard hair','Micron','Scouring'],['cashmere']],
['Denier','Measurements','den, D, linear density',
'Denier measures mass per length: a 9,000-meter length with a mass of 1 gram is 1 denier. A larger number means more mass for the same length. The unit may describe an individual filament or a whole yarn, so the object being measured must accompany the number.',
'A 90-denier yarn has a linear density of 10 tex because tex uses grams per 1,000 meters. If that yarn contains 30 equal filaments, each is nominally 3 denier. These are calculated examples, not measurements of a particular fabric.',
'Denier is not a direct diameter, thread count or fabric-weight measurement. Material density, cross-sectional shape, filament count and fabric construction prevent a simple universal conversion from denier to softness, opacity or durability.',['Filament','Micron','Staple'],['denier']],
['Drape','Fabric performance','drapability, fabric fall',
'Drape describes the folds and silhouette a fabric forms when supported at some points and allowed to hang elsewhere. Its behavior reflects several interacting properties, including bending resistance, deformation between yarns and its own weight. Drape is experienced at the fabric level, so composition alone is an incomplete description.',
'Compare two equally sized swatches over the same rounded support. One may form broad, structured folds while the other falls into smaller folds. That comparison helps a maker choose between a sculptural jacket and a flowing skirt without treating either result as universally better.',
'Drape and hand are related but different observations: one concerns hanging behavior, the other touch. A fabric can feel soft in the hand yet retain a relatively structured silhouette. Evaluate a representative finished sample.',['Hand','Weaving','Finishing'],['drape','hand']],
['Dyeing','Color & finishing','dyed, yarn-dyed, piece-dyed, garment-dyed',
'Dyeing introduces color to a textile substrate. It can take place at the fiber, yarn, fabric or garment stage, and the choice affects production planning and the appearance that can be created. Fiber chemistry and the intended color determine which dye systems and processing conditions are suitable.',
'A yarn-dyed stripe can be built by arranging differently colored yarns before fabric formation. A piece-dyed fabric is colored after the cloth has been formed. These examples explain the processing stage, but do not establish the product’s resistance to washing or rubbing.',
'Color application and colorfastness are different questions. “Dyed” does not promise permanence under every exposure. Request test information appropriate to the intended use, and follow the finished garment’s care instructions.',['Finishing','Scouring','Warp & weft'],['dye','weavebasics']],
['Elastane','Fiber structure','spandex, LYCRA, stretch fiber',
'Elastane and spandex are generic names for the same class of highly extensible manufactured fiber. LYCRA is a brand name associated with this category, not the generic name of every stretch textile. The fiber is commonly incorporated with other materials so a fabric can extend and recover during use.',
'A cotton garment containing a small amount of elastane may stretch differently from an all-cotton garment. The percentage alone is insufficient to predict the result: the placement of the stretch yarn and the knitted or woven structure also need consideration.',
'A fabric can stretch through its construction without containing elastane. Conversely, an elastane percentage does not specify how much stretch occurs in each direction or how well the garment recovers. Check composition and finished-fabric behavior separately.',['Knitting','Weaving','Filament'],['lycra','bisfa']],
['Filament','Fiber structure','continuous filament, monofilament, multifilament',
'A filament is a very long fiber that can be used continuously rather than assembled from many short lengths. A monofilament yarn uses one filament; a multifilament yarn brings several together. Manufactured filaments may also be cut into finite lengths for staple-fiber processing.',
'Think of a continuous strand compared with a rope assembled from overlapping short pieces. Both can become useful yarns, but their construction differs. A yarn specification should identify whether a denier value refers to the complete multifilament yarn or to each filament.',
'Filament does not mean synthetic, and staple does not mean natural. Reeled silk provides a natural filament example. The words describe length and construction, while the fiber name describes material identity.',['Staple','Denier','Sliver'],['bisfa','staple']],
['Finishing','Color & finishing','finish, mechanical finishing, chemical finishing',
'Finishing changes textile appearance, touch or performance beyond its basic construction and coloration. Processes may act mechanically or use chemical treatments. Despite the name, finishing is not always the final operation in a manufacturing sequence. Its effects should be evaluated on the actual finished textile.',
'If two fabrics share the same composition and weave but have different surfaces, a finishing difference may help explain the result. Ask what treatment was applied, what property it is intended to change, and whether that property was measured after repeated care cycles.',
'A finish can alter the impression created by the underlying fiber. Initial softness or smoothness alone cannot identify the fiber or establish long-term performance. Avoid assuming that a treatment’s presence tells you its durability.',['Hand','Drape','Dyeing'],['finish']],
['Ginning','Processing','cotton gin, lint, seed cotton',
'Ginning separates cotton lint from seeds after harvesting. Cleaning operations remove additional unwanted material, and the prepared lint is compressed into bales for transport and later textile production. This is an early agricultural-processing stage, before a spinning mill turns the fiber into yarn.',
'In a cotton supply-chain record, distinguish seed cotton arriving at a gin from a lint bale leaving it. Those are different material forms. Keeping the stage clear makes it easier to interpret quantities and to understand why incoming and outgoing masses are not interchangeable.',
'Ginning does not mean spinning, combing or fabric washing. Nor does the gin’s location automatically identify the farm for every bale. An origin claim needs records that connect the relevant stages.',['Carding','Staple','Traceability'],['gin']],
['Greasy wool','Processing','raw wool, fleece, wool grease',
'Greasy wool is wool before raw-wool scouring removes much of its grease and accompanying contaminants. A raw fleece contains more than clean textile fiber: dirt, dust and suint, among other material, contribute to its mass. The amount varies with the fleece and its circumstances.',
'If comparing a raw fleece price with a clean-fiber price, first identify the mass basis. A kilogram of greasy wool is not equivalent to a kilogram of scoured fiber. Ask whether a quoted quantity or yield refers to the material before or after cleaning.',
'Greasy describes a processing state, not a wool breed or a softness grade. It also does not establish how the wool will perform once cleaned, spun, constructed and finished.',['Scouring','Carding','Worsted'],['scour']],
['Guard hair','Fiber structure','outer coat, coarse hair, underdown',
'Guard hair refers to the coarser outer component of a coat where it is distinguished from a finer undercoat. The distinction is especially useful when discussing cashmere preparation. The mixed raw coat and the selected fine textile fraction should not be treated as the same material specification.',
'For a fine animal-fiber purchase, ask whether the sample represents the raw coat or the dehaired product. A supplier’s fiber-diameter data should be interpreted alongside that description. A single average may not communicate the entire distribution of fine and coarse fibers.',
'Guard hair is not a synonym for all animal hair, and the term alone does not identify an animal species. Its relevance depends on the coat and the intended product.',['Dehairing','Micron','Hand'],['cashmere']],
['Hand','Fabric performance','handle, fabric feel, tactile properties',
'Hand, also called handle, is the tactile impression a textile gives when touched or manipulated. Useful descriptions identify specific qualities such as softness, stiffness, smoothness or surface roughness. The word gathers several sensations rather than naming one universal numerical property.',
'Compare swatches with the same handling action: stroke the surface, gently bend them and compress them. Record what you notice separately. “Smooth surface but firm body” is more informative to another maker than an unexplained claim of “excellent hand.”',
'Hand depends on the finished textile, not just its fiber label. Personal preference, fabric structure and finishing can change the assessment. A pleasant initial feel also does not prove durability or suitability for every skin-contact use.',['Drape','Finishing','Micron'],['hand']],
['Knitting','Fabric construction','knit, loops, weft knitting, warp knitting',
'Knitting forms fabric through connected yarn loops. Loop geometry distinguishes it from weaving, where yarn systems interlace. Weft and warp knitting arrange and supply yarns differently, and the resulting structures offer a wide range of surface patterns and mechanical behavior.',
'Look closely at a simple jersey fabric: its repeated loops explain why the material can deform in ways a tightly woven fabric may not. That does not mean every knit stretches equally. Yarn choice, loop dimensions and structure all influence the finished result.',
'Knit describes construction rather than composition. Cotton, wool and manufactured fibers can all be knitted. Do not assume that a knit contains elastane or that every knitted garment has the same care needs.',['Weaving','Elastane','Hand'],['knit']],
['Micron','Measurements','micrometer, micrometre, µm, μm, fiber diameter',
'A micron is one micrometer, equal to one millionth of a meter. It is commonly used for wool fiber diameter. A stated mean diameter summarizes a population of fibers rather than asserting that every fiber in the sample measures exactly that amount.',
'For scale, 20 microns equals 0.020 millimeters. If comparing two wool lots, ask whether their numbers were measured on comparable samples and whether information about variability accompanies the average. This makes the comparison more useful than reading the number as a product grade.',
'Diameter is different from fiber length, yarn linear density and fabric weight. A lower mean diameter alone cannot describe strength, pilling, origin or the performance of a completed garment.',['Denier','Guard hair','Staple'],['micron']],
['Pilling','Fabric performance','pills, bobbling, fabric pills',
'Pilling is the development of small entangled balls of fiber on a fabric surface. Wear and rubbing can bring fibers together into these visible clusters. High-contact regions, such as areas rubbed by sleeves or bags, may look different from less-exposed parts of the same garment.',
'When assessing a sweater, compare a frequently rubbed area with a protected area. Record the exposure and care history before drawing conclusions. A laboratory pilling result is also meaningful only with its method and test conditions; it is not a guarantee for every wearer.',
'Pills are not the same as loose lint, and pilling alone does not identify fiber composition. Follow garment care guidance and use any removal method cautiously to avoid damaging the underlying fabric.',['Staple','Hand','Finishing'],['pill','pillcare']],
['Post-consumer','Claims & sourcing','post-consumer recycled, PCR',
'Post-consumer material comes from products that have reached an end user and are recovered after their intended use. In a recycled-content claim, the term describes the source stage of the input. It does not by itself specify whether the input was a textile, packaging or another product.',
'A used garment collected for fiber recovery and a used plastic bottle processed into a textile feedstock have different original forms. Ask which input a claim refers to, what proportion of the final material it represents, and how that proportion is documented.',
'Recycled input does not automatically mean the finished product can be recycled again in your local system. The applicable certification definition and evidence should accompany a specific commercial claim.',['Pre-consumer','Chain of custody','Traceability'],['toolkit']],
['Pre-consumer','Claims & sourcing','post-industrial, manufacturing waste',
'Pre-consumer material is recovered from manufacturing before a product reaches its end user. Eligibility for a recycled-content claim depends on the applicable definition. Rework or scrap returned within its originating process may be treated differently from material diverted from a separate waste stream.',
'For cutting-room offcuts, ask where they were generated, how they were collected and what recycling operation transformed them. The example describes a possible input stream; it does not certify the eligibility of every offcut under every scheme.',
'The rules can change. Textile Exchange published 2026 updates concerning reclaimed-material tracking and an alternative definition for certain pre-consumer plastics. Check the effective standard and claim scope instead of treating an older general definition as a current certification decision.',['Post-consumer','Traceability','Chain of custody'],['toolkit','policies']],
['Regenerated cellulose','Fiber structure','regenerated cellulosic, rayon, viscose, lyocell, modal',
'Regenerated cellulose fibers are manufactured by dissolving cellulose and forming it again as fiber. Viscose, modal and lyocell belong to this broader family, but their processes differ. Lenzing describes direct dissolution for lyocell and a chemical derivatization step before dissolution in its viscose route.',
'The source of the cellulose and the name of the resulting fiber answer different questions. A wood or other plant feedstock does not mean the final fiber was mechanically extracted intact from that plant. Ask for both the generic fiber name and its feedstock information.',
'Regenerated is not synonymous with recycled: the cellulose may originate from virgin or recovered inputs. A renewable feedstock also does not establish the environmental performance of the full production process.',['Bast fiber','Cottonization','Filament'],['lenzing']],
['Retting','Processing','dew retting, field retting, water retting',
'Retting loosens the tissues that bind useful bast fibers within a plant stem. European flax production commonly uses field retting, where natural conditions and biological action help make the fibers separable. The process prepares stems for mechanical extraction rather than producing finished yarn.',
'A flax journey may show pulling, retting and then scutching. Read those as distinct transformations: harvesting the stem, loosening binding tissues and separating the usable fiber from woody material. Keeping them separate makes processing descriptions easier to follow.',
'Retting practices depend on crop and production route. Do not assume that every bast fiber is water-retted or that a process name establishes its water, energy or pollution impacts.',['Bast fiber','Scutching','Cottonization'],['flax']],
['Scouring','Processing','washed wool, raw wool scouring, textile cleaning',
'Scouring is a cleaning operation whose specific purpose depends on the substrate. In raw wool, washing and rinsing remove grease and contaminants before later processing. This prepares a more usable fiber mass; it is different from aligning fibers or selecting a length distribution.',
'A wool mill can receive greasy fleece and supply scoured loose wool before another facility performs top-making. The words “scoured” and “combed” therefore describe separate changes. Ask which material form is actually being supplied before comparing prices or quantities.',
'Industrial scouring is not a home-care instruction. A finished garment may include dyes, finishes, lining and construction that require a particular wash or cleaning method. Follow the product’s label.',['Greasy wool','Carding','Top'],['wool','scour']],
['Scutching','Processing','scutched flax, shives, flax extraction',
'Scutching mechanically separates useful flax fibers from the woody portions of retted stems. It belongs to fiber extraction, before yarn spinning. The process produces useful fiber fractions and other outputs rather than converting the entire stem into a single textile material.',
'A lot described as scutched flax is at a different stage from spun linen yarn. If comparing material offers, ask which preparation stages still remain and whether the material is a long-fiber or shorter-fiber fraction. These distinctions matter for the planned processing route.',
'Scutching is not the same as retting: retting loosens tissues, while scutching carries out mechanical separation. It is also not a synonym for cotton ginning, which separates seed hairs from seeds.',['Retting','Bast fiber','Ginning'],['flax','flaxmap']],
['Sliver','Processing','card sliver, drawn sliver, fiber strand',
'A sliver is a continuous, largely untwisted strand made from many individual fibers. It is an intermediate form that makes a loose fiber mass easier to handle, combine and draw during preparation for spinning. Its continuity does not imply that its constituent fibers are continuous filaments.',
'A card may deliver a strand of short cotton fibers as sliver. Later operations can combine or draw such strands before yarn formation. Imagine overlapping short pieces arranged into a continuous ribbon: the ribbon is continuous even though each piece ends.',
'Sliver and finished yarn should not be used interchangeably. A sliver has not acquired the same structure or handling strength as the yarn ultimately made from it. Specify the processing stage when discussing a sample.',['Carding','Top','Staple'],['sliver','wool']],
['Staple','Fiber structure','staple fiber, staple fibre, cut staple, staple length',
'Staple fibers have finite lengths and are assembled into yarn through overlap and an appropriate spinning process. Cotton and wool are familiar natural examples; manufactured fibers can also be cut to staple lengths. The length distribution matters, not just the longest fiber in a sample.',
'A polyester textile can use continuous-filament yarn or spun yarn made from cut polyester staple. The polymer name can therefore remain the same while the yarn construction changes. Ask for the fiber form when a composition label does not explain the texture you observe.',
'Staple is not a quality rating or a synonym for natural fiber. “Long staple” needs context: relevant lengths and processing expectations differ between cotton, wool and other fiber systems.',['Filament','Combing','Sliver'],['staple']],
['Top','Processing','wool top, combed top, top-making',
'Top is the prepared, combed strand used in the worsted wool route. Top-making brings together preparation stages that improve alignment and remove short fibers and remaining contaminants. The resulting strand is an intermediate material that will be further processed before becoming yarn.',
'A top supplier and a yarn spinner may be separate businesses. An order for wool top therefore does not necessarily include spinning. When following a material journey, identify the stage where a prepared fiber strand becomes a specified yarn.',
'Top is not the same as loose scoured wool or finished worsted cloth. It is also not a universal name for every carded strand. Ask whether the material is card sliver, combed top, roving or spun yarn.',['Combing','Sliver','Worsted'],['top']],
['Traceability','Claims & sourcing','provenance, origin records, supply-chain tracking',
'Traceability is the ability to follow specified information about a material through recorded stages. A useful claim identifies what is traced, how far back the records reach and which links are supported. A map of plausible locations is not, by itself, a record for a specific product.',
'For a garment, you might know the sewing factory but not the spinning mill or fiber origin. State that boundary clearly. To investigate further, ask for links between the product, batch records, purchases and the relevant upstream facilities.',
'Traceability and certification are different ideas. A traceable material is not automatically certified to an environmental standard, and a general supplier certificate does not answer every product-origin question. Fibers of Earth routes remain illustrative.',['Chain of custody','Ginning','Post-consumer'],['custody']],
['Warp & weft','Fabric construction','warp and weft, ends, picks, filling, selvedge, selvage',
'Warp and weft are the principal yarn systems in weaving. Warp yarns run lengthwise through the loom, while weft, also called filling, crosses them. The sequence of interlacing produces the weave, and the two systems may use different yarns, colors or materials.',
'On a woven sample with its original selvedge, the warp direction runs along that edge. Identify both directions before comparing stretch or cutting a pattern piece. A fabric can behave differently lengthwise and crosswise even when its overall composition is unchanged.',
'These are structural directions, not fiber names. The terminology also should not be applied casually to the loop rows and columns of ordinary weft knitting, which uses a different construction.',['Weaving','Knitting','Dyeing'],['weavebasics']],
['Weaving','Fabric construction','woven fabric, loom, interlacing',
'Weaving constructs fabric by interlacing yarn systems. In a conventional loom, warp yarns are arranged lengthwise and weft is inserted across them. Different interlacing sequences produce structures such as plain weave, twill and satin; those structures are not themselves fiber types.',
'Two fabrics can both be cotton while one uses a plain weave and the other a twill. A composition label identifies the material, while a construction description helps explain its surface and behavior. Both are needed to describe the textile usefully.',
'Woven does not automatically mean rigid, waterproof or non-stretch. Yarn selection, interlacing, density and finishing influence the final performance. Compare finished samples for the use you have in mind.',['Warp & weft','Knitting','Drape'],['weave']],
['Worsted','Processing','worsted-spun, worsted wool, woollen, woolen',
'In textile manufacturing, worsted describes a preparation and spinning route using aligned, combed fibers. It contrasts with the woollen route, which uses a different preparation sequence. The processing distinction helps explain yarn character, but does not by itself prescribe a particular garment or weave.',
'A worsted yarn can be used in different fabric constructions. When reading a supplier’s description, separate the processing route from fiber composition, yarn count and the eventual knitted or woven structure. That prevents one familiar word from standing in for a complete specification.',
'Hand-knitting labels also use “worsted weight” as a yarn-size category. That usage does not establish that the yarn was manufactured by the worsted wool-processing route. Confirm which meaning the speaker intends.',['Top','Combing','Carding'],['iwto','top','weights']]
];
const slug=term=>term.toLowerCase().replace(/ & /g,'-and-').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const base=rows.map(([term,category,aliases,explanation,example,caution,related,sources])=>({term,category,aliases:aliases.split(', '),definition:definitions[term],explanation,example,caution,related,sources}));
const added=glossaryAdditions.map(t=>({...t,sources:[]}));
export const glossaryEntries=[...base,...added].map(t=>{const d=glossaryDepth[t.term]||{};return {...t,id:slug(t.term),deeper:t.deeper||d.deeper||'',origins:t.origins||d.origins||'',related:[...new Set([...t.related,...(d.related_add||[])])],refs:[...(t.refs||[]),...(d.refs||[])],reviewed};});
const known=new Set(glossaryEntries.map(t=>t.term));
for(const t of glossaryEntries)t.related=t.related.filter(name=>known.has(name)&&name!==t.term);
export const glossaryById=Object.fromEntries(glossaryEntries.map(t=>[t.id,t]));
export const glossaryCategories=[...new Set(glossaryEntries.map(t=>t.category))].sort();
export const glossaryFieldLabels={term:'Term',aliases:'Also searched as',definition:'Short answer',category:'Topic',explanation:'In detail',deeper:'The science and numbers',origins:'Origins and history',example:'A practical example',caution:'What to distinguish'};
let termIndex;
const index=()=>termIndex??=createIndex(glossaryEntries,{term:10,aliases:7,definition:3,category:1,explanation:1.2,deeper:1,origins:.8,example:.6,caution:.6},{aliases:{topic:'category',category:'category',history:'origins',science:'deeper'}});
// Ranked search with the fields each term matched; without a query, terms are alphabetical.
export function searchTerms({q='',category='',letter=''}={}){
 const keep=t=>(!category||t.category===category)&&(!letter||t.term[0]===letter);
 if(!String(q).trim())return glossaryEntries.filter(keep).sort((a,b)=>a.term.localeCompare(b.term,'en')).map(term=>({term,score:0,matched:{}}));
 return index().search(q,{filter:keep}).map(r=>({term:r.doc,score:r.score,matched:r.matched}));
}
export function findTerms(opts={}){return searchTerms(opts).map(r=>r.term);}
export function suggestTerms(q){return index().suggest(q);}
